MyBlog/urls.py
import xadmin
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
	# url(r'^admin/', admin.site.urls),
	url(r'', include('blog.urls')),
	url(r'', include('user.urls')),
	url(r'', include('comment.urls')),  # 评论,
	url(r'', include('other.urls')),  # 评论,
	url(r'mdeditor/', include('mdeditor.urls')),  # markdown
	# url(r'^captcha/', include('captcha.urls')),  # captcha,
	url(r'^search/', include('haystack.urls')),
	url(r'xadmin/', include(xadmin.site.urls)),  # xadmin
]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'blog'
urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),  # 首页
	# url(r'^index/$', views.IndexView.as_view()),  # 首页
	url(r'^article/(?P<id>\d+)$', views.ArticleView.as_view(), name='article'),  # 详情页
	url(r'^article/archives', views.ArchivesView.as_view(), name='archives'),
	url(r'^article/blog$', views.BlogListView.as_view(), name='blog'),
	url(r'^article/blogdata', views.BlogListDataView.as_view()),
	url(r'^article/(?P<type>\w+)/(?P<id>\w+)$', views.ArticleListView.as_view(), name='type'),
]

other/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'other'
urlpatterns = [
	url(r'^about', views.AboutMeView.as_view(), name='about'),  # 评论
	url(r'^refresh', views.UpdateStaticFileView.as_view(), name='flush'),  # 评论
]

user/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'user'
urlpatterns = [
	url(r'^register$', views.RegisterView.as_view(), name='register'),  # 注册
	url(r'^register/sendtomes', views.SendToMes.as_view(), name='sms'),  # 发送短信
	url(r'^login/$', views.LoginView.as_view(), name='login'),  # 登录
	url(r'^logout/$', views.LoginOutView.as_view(), name='logout'),  # 登出
]

blog/models.py
import logging
import os

import markdown
from django.db import models
from django.utils.html import strip_tags
from mdeditor.fields import MDTextField

from MyBlog.settings import BASE_DIR
from user.models import User
from utils.constants import EXCERPT_LENGTH
import django.utils.timezone as timezone


class Category(models.Model):
	"""分类"""
	# objects = OtherManager()
	name = models.CharField(max_length=100, verbose_name='分类')

	class Meta:
		verbose_name = '分类'  # 在admin站点中显示的名称
		verbose_name_plural = verbose_name  # 显示的复数名称

	def __str__(self):
		return self.name


class Tag(models.Model):
	"""标签"""
	name = models.CharField(max_length=100, verbose_name='标签', unique=True)

	class Meta:
		verbose_name = '标签'  # 在admin站点中显示的名称
		verbose_name_plural = verbose_name  # 显示的复数名称

	def __str__(self):
		return self.name


class Article(models.Model):
	"""文章"""
	title = models.CharField(max_length=100, verbose_name='标题')
	excerpt = models.TextField(max_length=200, blank=True, verbose_name='摘要')
	created_time = models.DateTimeField(default=timezone.now, verbose_name='发布日期')
	modified_time = models.DateTimeField(auto_now=True, verbose_name='修改日期')
	author = models.ForeignKey(User, default=None, on_delete=models.CASCADE, verbose_name='作者')
	category = models.ForeignKey(Category, default=None, on_delete=models.CASCADE, verbose_name='分类')
	body = MDTextField(verbose_name='内容')
	views = models.PositiveIntegerField(default=0, verbose_name='浏览量')
	tags = models.ManyToManyField(Tag, blank=True, verbose_name='标签')
	is_show = models.BooleanField(default=True, verbose_name='是否显示')
	is_banner = models.BooleanField(default=False, verbose_name='是否轮播')
	image = models.ImageField(upload_to='upload', null=True, blank=True,
							  verbose_name='图(820*200)')

	# 浏览量
	def add_views(self):
		self.views += 1
		self.save(update_fields=['views'])

	# 获取图片的url
	def image_url(self):
		if not self.image:
			return '/static/images/upload/default_image.png'
		return self.image.url

	class Meta:
		verbose_name = '文章'  # 在admin站点中显示的名称
		verbose_name_plural = verbose_name  # 显示的复数名称
		ordering = ['-created_time', ]

	def save(self, *args, **kwargs):
		"""保存时,自动生成摘要"""
		if not self.excerpt:
			md = markdown.Markdown(['extra', 'codehilite', 'toc', ])
			excerpt = strip_tags(md.convert(self.body))[:EXCERPT_LENGTH]
			if len(excerpt) < EXCERPT_LENGTH:
				self.excerpt = excerpt
			else:
				self.excerpt = excerpt + '......'

		# 调用父类的 save 方法将数据保存到数据库中
		super(Article, self).save(*args, **kwargs)

		if self.image:
			"""如果上传图片,更新静态资源"""
			sh_file = os.path.join(BASE_DIR, 'py_collecte.sh')
			status = os.system('bash %s' % sh_file)
			if status != 0:
				logging.error('静态文件更新状态:%s' % status)

	def __str__(self):
		return self.title

comment/models.py
import logging

from django.db import models

# Create your models here.
from django.http import JsonResponse

from blog.models import Article
from user.models import User
from utils.error_code import ErrorCode


class Comment(models.Model):
	"""评论表,自关联多对多"""
	content = models.CharField(max_length=256, verbose_name='评论')
	created_time = models.DateTimeField(auto_now_add=True, verbose_name='评论时间')
	user = models.ForeignKey(User, default=None, on_delete=models.CASCADE, verbose_name='评论人')
	article = models.ForeignKey(Article, default=None, on_delete=models.CASCADE, verbose_name='文章')
	parent = models.ForeignKey('self', default=None, on_delete=models.CASCADE, null=True, blank=True,
							   verbose_name='父评论')
	floor = models.IntegerField(default=0, verbose_name='楼层')

	@staticmethod
	def check_create(user_id, content, article_id, comment_id):
		if not all([content, article_id]):
			return JsonResponse({'error': ErrorCode.PARAMERR})
		if content.isspace():  # 如果content的内容为空格等
			return JsonResponse({'error': ErrorCode.COMMENTNONEERR})
		if not article_id:
			return JsonResponse({'error': ErrorCode.PARAMERR})
		# 尝试保存新评论
		try:
			comment = Comment()

			if comment_id:
				# 给评论评论
				comment.parent_id = comment_id
			# 给文章评论
			comment.content = content
			comment.article_id = article_id
			comment.user_id = user_id
			try:
				comment.floor = Comment.objects.filter(article_id=article_id).count() + 1
			except Exception as e:
				logging.error(e)
				pass
			comment.save()
		except Exception as e:
			logging.error(e)
			return JsonResponse({'error': ErrorCode.DATAERR})

		data = dict()
		data['id'] = comment.id
		data['article_id'] = comment.article_id
		data['content'] = comment.content
		data['user'] = comment.user.username
		data['img_url'] = comment.user.icon_url()
		data['floor'] = comment.floor
		data['created_time'] = comment.created_time.strftime('%Y年%m月%d日 %H:%S')
		return JsonResponse({"error": ErrorCode.OK, 'data': data})

	class Meta:
		ordering = ["-created_time", ]
		verbose_name = '评论'  # 在admin站点中显示的名称
		verbose_name_plural = verbose_name  # 显示的复数名称

	def __str__(self):
		return self.content

templates/allblog.html
{% extends 'base.html' %}
{% load sidebar %}
{% block titleBlcok %}
	全部博客
{% endblock %}

{% block content00Block %}
	<div id="focusslide" class="carousel slide" data-ride="carousel">

	</div>
	<div class="title">
	<h3><i class="fa fa-book mr-1"></i> 全部博客</h3>
{% endblock %}
{% block content01Block %}
	</div>
	</div>
{% endblock %}

{% block jsBlock %}
	<script src="/static/js/bloglist.js"></script>
{% endblock %}

templates/article.html
{% extends 'base.html' %}
{% block titleBlcok %}
	{% if article %}
		{{ article.title }}
	{% else %}
		Blog
	{% endif %}
{% endblock %}

{% block content00Block %}
	<header class="article-header">
		<h1 class="article-title"><a href="{% url 'blog:article' article.id %}">{{ article.title }}</a></h1>
		<div class="article-meta"> <span class="item article-meta-time">
<time class="time" data-toggle="tooltip" data-placement="bottom" title="时间：{{ article.created_time }}"><i
		class="glyphicon glyphicon-time"></i> {{ article.created_time }}</time>
</span> <span class="item article-meta-source" data-toggle="tooltip" data-placement="bottom"
			  title="作者：{{ article.author }}"><i
				class="glyphicon glyphicon-globe"></i> {{ article.author }}</span> <span
				class="item article-meta-category" data-toggle="tooltip" data-placement="bottom"
				title="分类：{{ article.category }}"><i class="glyphicon glyphicon-list"></i> <a href="#"
																							  title="">{{ article.category }}</a></span>
			<span
					class="item article-meta-views" data-toggle="tooltip" data-placement="bottom"
					title="浏览量：{{ article.views }}"><i
					class="glyphicon glyphicon-eye-open"></i> 共{{ article.views }}人围观</span> <span
					class="item article-meta-comment"
					data-toggle="tooltip"
					data-placement="bottom"
					title="评论：{{ article.comment_set.count }}"><i
					class="glyphicon glyphicon-comment"></i> {{ article.comment_set.count }}评论</span></div>
	</header>
	<article class="article-content">
		<p>
			{#			<img data-original="{{ article.image_url }}" src="{{ article.image_url }}" alt=""/>#}
		</p>
		{{ article.body | safe }}
	</article>
	<div class="article-tags"><i class="fa fa-tags mr-1"></i> 标签：
		{% for tag in article.tags.all %}
			<a href="{% url 'blog:type' 'tag' tag.id %}" rel="tag">
				{{ tag }}
			</a>
		{% endfor %}
	</div>
	<div class="title" id="comment">
		<h3>发表评论</h3>
	</div>
	<div id="respond">
		<form action="" method="post" id="comment-form">
			{% csrf_token %}
			<div class="comment">
				<div class="comment-box">
<textarea placeholder="欢迎发表评论" name="comment" id="comment-textarea" cols="100%" rows="3"
		  tabindex="1" class="textarea"></textarea>
					<div class="comment-ctrl">
						<div class="comment-prompt"><i class="fa fa-spin fa-circle-o-notch"></i> <span
								class="comment-prompt-text"></span></div>
						<input type="hidden" name="article_id" value="{{ article.id }}" class="articleid"/>
						<button type="button" name="comment-submit" id="comment-submit">评论
						</button>
					</div>
				</div>
			</div>
		</form>
	</div>
	<div id="postcomments">
		<ol class="commentlist">

			{% for comment in comments %}
				<li class="comment-content">
					<p style="float: right;"><a href="javascript:;" style="text-decoration:none;"
												class="switch"><i class="fa fa-mail-reply mr-1"></i> 回复</a> {{ comment.floor }}楼
					</p>
					<div class="comment-avatar"><img class="avatar" src="{{ comment.user.icon_url }}" alt=""/></div>
					<div class="comment-main">
						<p><span class="address">{{ comment.user.username }}</span>
							<span>
								{#如果是评论-评论#}
								{% if comment.parent %}
									回复:
									<span class="address">{{ comment.parent.user.username }}</span>
								{% endif %}
							</span>
							<span class="time">{{ comment.created_time }}</span><br/>{{ comment.content }}
						</p>
						<form class="innerhidden">
							<div id="div00">
								<textarea class="textarea"></textarea>
								<div id="div01" comment_id="{{ comment.id }}" article_id="{{ article.id }}">
									<input type="button" value="确定" class="reply"/>
								</div>
							</div>
						</form>

					</div>

				</li>

			{% endfor %}
			<div class='pagination'>
				{% if comments %}
					{% if comments.number|add:-3 > 0 %}
						<a href='?page=first'><span>首页</span></a>
					{% endif %}
					{% if comments.has_previous %}
						<a href='?page={{ comments.previous_page_number }}'><span>上一页</span></a>
					{% endif %}
					{% for page in comments.paginator.page_range_ext %}
						{% if page == comments.number %}
							<a title='当前页:{{ page }}'
							   style="background: #3399CC;color: white"><span>{{ page }}</span></a>
						{% else %}
							<a href='?page={{ page }}' title='{{ page }}'><span>{{ page }}</span></a>
						{% endif %}
					{% endfor %}
					{% if comments.has_next %}
						<a href='?page={{ comments.next_page_number }}'><span>下一页</span></a>
					{% endif %}
					{% if comments.number|add:2 < comments.paginator.num_pages %}
						<a href='?page={{ comments.paginator.num_pages|add:999 }}'><span>末页</span></a>
					{% endif %}
				{% endif %}
			</div>
		</ol>
	</div>
	</div>
{% endblock %}

{% block jsBlock %}
	<script rel="javascript" type="text/javascript" src="/static/js/other.js"></script>
{% endblock %}

{% block tagBlock %}
{% endblock %}

templates/base.html
{% load sidebar %}
<!doctype html>
<html lang="zh-CN">
<head>
	<meta charset="utf-8">
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>
		{% block titleBlcok %}

		{% endblock %}
	</title>
	<link rel="stylesheet" type="text/css" href="/static/css/github-markdown.css">
	<link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/static/css/nprogress.css">
	<link rel="stylesheet" type="text/css" href="/static/css/style.css">
	<link rel="stylesheet" type="text/css" href="/static/css/font-awesome.min.css">
	<link rel="apple-touch-icon-precomposed" href="/static/images/icon/icon.png">
	<link rel="shortcut icon" href="/static/images/icon/favicon.ico">
	<link rel="stylesheet" href="/static/css/highlights/github.css">
	<script rel="javascript" type="text/javascript" src="/static/js/jquery-2.1.4.min.js"></script>
	<script rel="javascript" type="text/javascript" src="/static/js/nprogress.js"></script>
	<script rel="javascript" type="text/javascript" src="/static/js/jquery.lazyload.min.js"></script>
</head>

<body class="user-select">
<header class="header">
	<nav class="navbar navbar-default" id="navbar">
		<div class="container">
			<div class="header-topbar hidden-xs link-border">
				&nbsp;&nbsp;
				<ul class="site-nav topmenu">
					{% if request.session.is_login %}
						<li><a href="#" rel="nofollow">hi! {{ request.session.user_name }}</a></li>
						<li><a href="{% url 'user:logout' %}" rel="nofollow">登出</a></li>
					{% else %}
						<li><a href="{% url 'user:login' %}" rel="nofollow">Hi,请登录</a></li>
						<li><a href="{% url 'user:register' %}" class="register" rel="nofollow">注册</a></li>
					{% endif %}
				</ul>
			</div>
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
						data-target="#header-navbar" aria-expanded="false"><span class="sr-only"></span> <span
						class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span></button>
				<h1 class="logo hvr-bounce-in"><a href="{% url 'blog:index' %}" title=""><img
						src="/static/images/logo.png" alt=""></a></h1>
			</div>
			<div class="collapse navbar-collapse" id="header-navbar">
				<ul class="nav navbar-nav navbar-right">
					<li class="hidden-index active"><a data-cont="首 页" href="{% url 'blog:index' %}"><i class="fa fa-home mr-1"></i> 首 页</a></li>
					<li><a href="{% url 'blog:blog' %}"><i class="fa fa-book mr-1"></i> 博 客</a></li>
					<li><a href="{% url 'blog:archives' %}"><i class="fa fa-sitemap mr-1"></i> 归 档</a></li>
					{#					<li><a href="/">学习笔记</a></li>#}
					<li><a href="{% url 'other:about' %}"><i class="fa fa-hand-o-right mr-1"></i> About</a></li>
				</ul>
			</div>
		</div>
	</nav>
</header>
<section class="container">
	<div class="content-wrap">
		<div class="content">
			{% block content00Block %}
			{% endblock %}

			{% block tagBlock %}
				{% get_category as categories %}
				<div class="more">
					{% for category in categories %}
						<a href="{% url 'blog:type' 'category' category.id %}" category="{{ category.name }}">{{ category.name|capfirst }}</a>
					{% endfor %}
				</div>
			{% endblock %}

			{% block content01Block %}
			{% endblock %}
		</div>

		<aside class="sidebar">
			<div class="widget widget_search">
				<form class="navbar-form" action="{% url 'haystack_search' %}" method="get">
					<div class="input-group">
						<input type="text" name="q" class="form-control" size="35" placeholder="请输入关键字"
							   maxlength="15" autocomplete="off">
						<span class="input-group-btn"><button class="btn btn-default btn-search" name="search"
															  type="submit">搜索</button></span>
					</div>
				</form>
			</div>
			<div class="widget widget_sentence">
				<h3><i class="fa fa-calendar mr-1"></i> 每日一句</h3>
				<div class="widget-sentence-content">
					<h4> {% now "Y年m月d日 H:i" %} </h4>
					{% everyday_motto as mottos %}
					<p>
						{% for motto in mottos %}
							{{ motto }}
						{% endfor %}

					</p>
				</div>
			</div>
			<div class="widget widget_hot">
				<h3><i class="fa fa-fire mr-1"></i> 热门文章</h3>
				{% get_hot_articles as sidebar_articles %}
				<ul>
					{% for article in sidebar_articles %}
						<li><a href="{% url 'blog:article'  article.id %}"><span class="thumbnail">
							<img class="thumb" data-original="{{ article.image_url }}" src="{{ article.image_url }}"
								 alt=""></span><span
								class="text">{{ article.title }}</span><span class="muted"><i
								class="glyphicon glyphicon-time"></i> {{ article.created_time }} </span><span
								class="muted"><i
								class="glyphicon glyphicon-eye-open"></i> {{ article.views }}</span></a></li>
					{% endfor %}
				</ul>
			</div>
			<div class="widget">
				{# article-tags #}
				{% get_tags as tags %}
				<h3><i class="fa fa-tags mr-1"></i> 标签</h3>
				{% for tag in tags %}
					<a href="{% url 'blog:type' 'tag' tag.id %}"
					   class="tags">{{ tag.name|capfirst }}({{ tag.article_set.count }})</a>
				{% endfor %}
			</div>
		</aside>


	</div>
</section>
<footer class="footer">
	<div class="container">
{#		<p>&copy; 2016 <a href="#">spiritblog.com</a> &nbsp; <a href="#" target="_blank"#}
{#																rel="nofollow">豫ICP备20151109-1</a> &nbsp; <a#}
{#				href="#" target="_blank" class="sitemap">网站地图</a></p>#}
	</div>
	<div id="gotop"><a class="gotop"></a></div>
</footer>
<script rel="javascript" type="text/javascript" src="/static/js/bootstrap.min.js"></script>
<script rel="javascript" type="text/javascript" src="/static/js/jquery.ias.js"></script>
<script rel="javascript" type="text/javascript" src="/static/js/scripts.js"></script>
{% block jsBlock %}

{% endblock %}

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block titleBlcok %}
	Home|首页
{% endblock %}

{% block content00Block %}
	<div id="focusslide" class="carousel slide" data-ride="carousel">
	<ol class="carousel-indicators">
		<li data-target="#focusslide" data-slide-to="0" class="active"></li>
		<li data-target="#focusslide" data-slide-to="1"></li>
		<li data-target="#focusslide" data-slide-to="2"></li>
	</ol>
	<div class="carousel-inner" role="listbox">
		{% for article in banner_articles %}
			{% if forloop.counter == 1 %}
				<div class="item active">
			{% else %}
				<div class="item">
			{% endif %}
		<a href="{% url 'blog:article'  article.id %}" target="_blank">
			<img src="{{ article.image_url }}"
				 alt="" class="img-responsive"></a>
		</div>
		{% endfor %}
		</div>
		<a class="left carousel-control" href="#focusslide" role="button" data-slide="prev" rel="nofollow">
			<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> <span
				class="sr-only">上一个</span> </a> <a class="right carousel-control" href="#focusslide"
												   role="button" data-slide="next" rel="nofollow"> <span
			class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> <span
			class="sr-only">下一个</span> </a></div>
	<div class="title">
	<h3><i class="fa fa-globe mr-1"></i> 最新发布</h3>
{% endblock %}
{% block content01Block %}
	</div>
	{% for article in articles %}
		<article class="excerpt excerpt-1"><a class="focus" href="{% url 'blog:article'  article.id %}" title="">
			<img class="thumb"
				 data-original="{{ article.image_url }}"
				 src="{{ article.image_url }}"
				 alt=""></a>
			<header><a class="cat"
					   href="{% url 'blog:type' 'category' article.category.id %} ">{{ article.category }}<i></i></a>
				<h2><a href="{% url 'blog:article' article.id %}" title="">{{ article.title }}</a></h2>
			</header>
			<p class="meta">
				<time class="time"><i class="glyphicon glyphicon-time"></i>{{ article.created_time }}</time>
				<span class="views"><i
						class="glyphicon glyphicon-eye-open"></i> 共{{ article.views }}人围观</span>
				<a class="comment" href="article.html#comment"><i class="glyphicon glyphicon-comment"></i>
					{{ article.comment_set.count }}条评论</a>
			</p>
			<p class="note">{{ article.excerpt }}</p>
		</article>
	{% endfor %}
	{#分页,articles当前页#}
	<div class='pagination'>
		{% if articles %}
			{% if articles.number|add:-3 > 0 %}
				<a href='?page=first'><span>首页</span></a>
			{% endif %}
			{% if articles.has_previous %}
				<a href='?page={{ articles.previous_page_number }}'><span>上一页</span></a>
			{% endif %}
			{% for page in articles.paginator.page_range_ext %}
				{% if page == articles.number %}
					<a title='当前页:{{ page }}' style="background: #3399CC;color: white"><span>{{ page }}</span></a>
				{% else %}
					<a href='?page={{ page }}' title='{{ page }}'><span>{{ page }}</span></a>
				{% endif %}
			{% endfor %}
			{% if articles.has_next %}
				<a href='?page={{ articles.next_page_number }}'><span>下一页</span></a>
			{% endif %}
			{% if articles.number|add:2 < articles.paginator.num_pages %}
				<a href='?page={{ articles.paginator.num_pages|add:999 }}'><span>末页</span></a>
			{% endif %}
		{% endif %}
	</div>
	</div>
{% endblock %}

templates/tags.html
{% extends 'base.html' %}
{% load sidebar %}
{% block titleBlcok %}
	{{ type|type_filter }}: {{ name|capfirst }}
{% endblock %}

{% block content00Block %}
	<div id="focusslide" class="carousel slide" data-ride="carousel">

	</div>
	<div class="title">
	<h3>{{ type|type_filter }}: {{ name|capfirst }}</h3>
{% endblock %}
{% block content01Block %}
	</div>
	{% for article in articles %}
		<article class="excerpt excerpt-1"><a class="focus" href="/article/{{ article.id }}" title="">
			<img class="thumb"
				 data-original="{{ article.image_url }}"
				 src="{{ article.image_url }}"
				 alt=""></a>
			<header><a class="cat" href="/article/category/{{ article.category.id }}">{{ article.category }}<i></i></a>
				<h2><a href="/article/{{ article.id }}" title="">{{ article.title }}</a></h2>
			</header>
			<p class="meta">
				<time class="time"><i class="glyphicon glyphicon-time"></i>{{ article.created_time }}</time>
				<span class="views"><i
						class="glyphicon glyphicon-eye-open"></i> 共{{ article.views }}人围观</span>
				<a class="comment" href="#"><i class="glyphicon glyphicon-comment"></i>
					{{ article.comment_set.count }}条评论</a>
			</p>
			<p class="note">{{ article.excerpt }}</p>
		</article>
	{% endfor %}
	{#分页#}
	<div class='pagination'>
		{% if articles.number != 1 %}
			<a href='?page=first'><span>首页</span></a>
		{% endif %}
		{% if articles.has_previous %}
			<a href='?page={{ articles.previous_page_number }}'><span>上一页</span></a>
		{% endif %}
		{% for page in articles.paginator.page_range %}
			{% if page == articles.number %}
				<a title='当前页:{{ page }}' style="background: #3399CC;color: white"><span>{{ page }}</span></a>
			{% else %}
				<a href='?page={{ page }}' title='{{ page }}'
				><span>{{ page }}</span></a>
			{% endif %}
		{% endfor %}
		{% if articles.has_next %}
			<a href='?page={{ articles.next_page_number }}'><span>下一页</span></a>
		{% endif %}
		{% if articles.number != articles.paginator.num_pages %}
			<a href='?page={{ articles.paginator.num_pages|add:999 }}'><span>末页</span></a>
		{% endif %}
	</div>
	</div>
{% endblock %}

templates/type.html
{% extends 'base.html' %}
{% load sidebar %}
{% block titleBlcok %}
	{{ type|type_filter }}: {{ name|capfirst }}
{% endblock %}

{% block content00Block %}
	<div id="focusslide" class="carousel slide" data-ride="carousel">

	</div>
	<div class="title">
	<h3>{{ type|type_filter }}: {{ name|capfirst }}</h3>
{% endblock %}
{% block content01Block %}
	</div>
	{% for article in articles %}
		<article class="excerpt excerpt-1"><a class="focus" href="/article/{{ article.id }}" title="">
			<img class="thumb"
				 data-original="{{ article.image_url }}"
				 src="{{ article.image_url }}"
				 alt=""></a>
			<header><a class="cat" href="/article/category/{{ article.category.id }}">{{ article.category }}<i></i></a>
				<h2><a href="/article/{{ article.id }}" title="">{{ article.title }}</a></h2>
			</header>
			<p class="meta">
				<time class="time"><i class="glyphicon glyphicon-time"></i>{{ article.created_time }}</time>
				<span class="views"><i
						class="glyphicon glyphicon-eye-open"></i> 共{{ article.views }}人围观</span>
				<a class="comment" href="#"><i class="glyphicon glyphicon-comment"></i>
					{{ article.comment_set.count }}条评论</a>
			</p>
			<p class="note">{{ article.excerpt }}</p>
		</article>
	{% endfor %}
	{#分页#}
	<div class='pagination'>
		{% if articles.number|add:-3 > 0 %}
			<a href='?page=first'><span>首页</span></a>
		{% endif %}
		{% if articles.has_previous %}
			<a href='?page={{ articles.previous_page_number }}'><span>上一页</span></a>
		{% endif %}
		{% for page in articles.paginator.page_range %}
			{% if page == articles.number %}
				<a title='当前页:{{ page }}' style="background: #3399CC;color: white"><span>{{ page }}</span></a>
			{% else %}
				<a href='?page={{ page }}' title='{{ page }}'
				><span>{{ page }}</span></a>
			{% endif %}
		{% endfor %}
		{% if articles.has_next %}
			<a href='?page={{ articles.next_page_number }}'><span>下一页</span></a>
		{% endif %}
		{% if articles.number|add:2 < articles.paginator.num_pages %}
			<a href='?page={{ articles.paginator.num_pages|add:999 }}'><span>末页</span></a>
		{% endif %}
	</div>
	</div>
{% endblock %}